[package]
name = "obd2"
description = "Utility for reading data from a vehicle over OBD-II"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rsammelson/obd2"
version = "0.2.0-pre3"
edition = "2021"

[dependencies]
env_logger = "0.10"
log = "0.4.8"
serial-rs = "0.2.1"
thiserror = "1.0.15"
